
## Introduction to R

- Date: 15th March 2018, 6 - 7pm
- Series: Wolfson College [Skills for Academic Success](https://www.wolfson.cam.ac.uk/study-skills)
- Location: [Roger Needham Room](http://www.wolfson.cam.ac.uk/tour/chancellorscentre), [Wolfson college](https://goo.gl/maps/aR6a5FWrLoR2), University of Cambridge, UK
- Register [here](https://www.eventbrite.co.uk/e/skills-for-academic-success-introduction-to-r-tickets-41949950431)


### Overview

This course provides a short beginners introduction to the R programming language and software environment for statistical computing and graphics. Sergio will demonstrate basic examples on how to input, explore, plot and output data in R. Everybody is welcome, if you would like to follow along with your laptop, please bring R and RStudio [downloaded and installed](https://www.rstudio.com/products/rstudio/download/) before the session.



### Outline

- Motivation
- Installing R and RStudio
- How can I find help?



### Motivation

- R is one of the most widely-used programming languages for data analysis and visualisation in academia and industry
- It is open-source and available in all platforms (Mac, Linux and Windows)
- Supported by a broad community of software developers and researchers who contribute R packages and libraries to many fields of research 
- It facilitates reproducibility in research and integration of all your analyses in individual scripts
- Easy to write documentation and code together using a free environment like [RStudio](https://www.rstudio.com/)

E.g. The New Zealand [Tourism Dashboard](https://mbienz.shinyapps.io/tourism_dashboard_prod/) uses R extensively to report statistics.



### Installing R and RStudio

- [Latest version of R](https://cran.r-project.org/)
- [RStudio Desktop Open Source License](https://www.rstudio.com/products/rstudio/download/)



### How can I find help?

- [Stack Overflow](https://stackoverflow.com/)
- [CRAN Task Views](https://cran.r-project.org/web/views/)
- [R-bloggers](https://www.r-bloggers.com/)
- [Quick-R](https://www.statmethods.net/)
- Local R groups, e.g. [R-ladies Cambridge](https://www.meetup.com/rladies-cambridge/)
- Type `?` followed my the name of the function that you'd like to explore

If you are interested in bioinformatics and computational biology, the following links might also be of interest:

- [Bioconductor](https://www.bioconductor.org/)
- [Biostars](https://www.biostars.org/)




### Running 

```{r}
print("Hello World")
```






### Materials

Blogs:

- [End-to-end visualization using ggplot2](https://rviews.rstudio.com/2017/08/14/end-to-end-visualization-using-ggplot2/)
- [ggplot2 - Easy way to mix multiple graphs on the same page](http://www.sthda.com/english/wiki/ggplot2-easy-way-to-mix-multiple-graphs-on-the-same-page)
- [Getting started with data visualization in R using ggplot2](http://www.storybench.org/getting-started-data-visualization-r-using-ggplot2/)

Books:

- [R for Data Science](http://r4ds.had.co.nz/)
- [Data Visualization for Social Science. A practical introduction with R and ggplot2](http://socviz.co/)

Courses:

- [CRUK-CI R crash course](https://bioinformatics-core-shared-training.github.io/r-crash-course/)
- [R for Reproducible Scientific Analysis](http://swcarpentry.github.io/r-novice-gapminder/)
- [Karl Broman's mini tutorials](http://kbroman.org/pages/tutorials.html)
- [Basic statistics and data handling with R](https://github.com/cambiotraining/stats-intro)
- [Scripting for data analysis (with R)](https://github.com/mrtnj/scripting_for_data_analysis)
- [An Introduction to Solving Biological Problems with R](http://cambiotraining.github.io/r-intro/)
- [Data Analysis and Visualisation using R](http://bioinformatics-core-shared-training.github.io/r-intermediate/): including dplyr and ggplot2
- Babraham institute basic/advanced R and ggplot2 [courses](http://www.bioinformatics.babraham.ac.uk/training/)
- R object-oriented programming and package development, [link1](http://lgatto.github.io/TeachingMaterial/) and [link2](http://logic.sysbiol.cam.ac.uk/teaching/advancedR/)
- [R course content for the CODATA-RDA Research Data Science Summer School](https://github.com/marioa/trieste)
- [Data carpentry course for biologists](https://jabberwocky.weecology.org/2016/11/14/fork-our-course-a-semester-long-data-carpentry-course-for-biologists/) by Ethan White
- [Cambridge's Data carpentry using R](https://tavareshugo.github.io/2017-09-11-cambridge/)

Perspectives:

- [Bioconductor: A test drive of a DNA-analysis toolkit in the cloud](https://www.nature.com/articles/d41586-017-07833-1)
- [Scientific computing: code alert](https://www.nature.com/nature/journal/v541/n7638/full/nj7638-563a.html)


### TODO
